# Generated by Django 4.2.16 on 2024-11-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Имя покупателя', models.CharField(max_length=50)),
                ('Баланс', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Возраст', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название игры', models.CharField(max_length=50)),
                ('Цена', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Размер файлов игры', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Описание', models.TextField()),
                ('Ограничение возраста 18+', models.BooleanField(default=False)),
                ('buyer', models.ManyToManyField(related_name='game', to='task1.buyer')),
            ],
        ),
    ]
